DROP TABLE lekarze CASCADE CONSTRAINTS;
DROP TABLE historia_pobytow CASCADE CONSTRAINTS;
DROP TABLE  historia_zabiegow CASCADE CONSTRAINTS;
DROP TABLE lekarze_specjalizacje CASCADE CONSTRAINTS;
DROP TABLE  oddzialy CASCADE CONSTRAINTS;
DROP TABLE  oddzialy_pielegniarki CASCADE CONSTRAINTS;
DROP TABLE  pacjenci CASCADE CONSTRAINTS;
DROP TABLE  pielegniarki CASCADE CONSTRAINTS;
DROP TABLE sale CASCADE CONSTRAINTS;
DROP TABLE specjalizacje CASCADE CONSTRAINTS;
DROP TABLE  specjalna_aparatura CASCADE CONSTRAINTS;
DROP TABLE  studenci CASCADE CONSTRAINTS;
DROP TABLE  zabiegi CASCADE CONSTRAINTS;

commit;